var path = require('path');

module.exports = function(grunt) {

  var existsSync = require('fs').existsSync;

  /**
   * Makefile directory option
   */
  var include = grunt.config.get('component.include');

  /**
   * COMPONENT_PATH
   */
  var componentPath = grunt.config.get('component.componentPath');

  grunt.registerTask('component', 'Build component"', function() {
    if ( !existsSync((include ? include + '/' : '') + 'Makefile') ){
      grunt.log.errorlns('`Makefile` generated by `component-create` should be placed to make this task to work!');
      return false;
    }
    var done = this.async()
      , args = ['build'];

    if (include) args.push('--directory', include);
    if (componentPath) process.env['COMPONENT_PATH'] = path.join(process.cwd(), componentPath);

    grunt.utils.spawn({cmd: 'make', args: args }, function(err, result, code){
        if ( err ) grunt.log.writeln(err);
        done(null, result);
    });
  });
};
